# Generated by Django 6.0.4 on 2026-04-16 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('gender_probability', models.FloatField()),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(max_length=20)),
                ('country_id', models.CharField(max_length=3)),
                ('country_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gender'], name='api_profile_gender_8edb79_idx'), models.Index(fields=['country_id'], name='api_profile_country_65dc5e_idx'), models.Index(fields=['age_group'], name='api_profile_age_gro_f7046d_idx')],
            },
        ),
    ]
