# Generated by Django 6.0.4 on 2026-04-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sample_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
